version: 2

models:
  - name: silver_rh_info
    description: "Silver layer - HR information with validated transportation method"
    columns:
      - name: id_salarie
        description: "Salarie ID - Primary key"
        tests:
          - unique
          - not_null
      - name: name_salarie
        description: "Employee first name"
        tests:
          - not_null
      - name: bu_salarie  
        description: "Employee business unit"
      - name: salaire_brut
        description: "Employee gross salary"
        tests:
          - dbt_utils.accepted_range:
                min_value: 0
      - name: type_contrat
        description: "Employee contract type"
        tests:
          - accepted_values:
              values: ['CDI', 'CDD']
      - name: jours_cp
        description: "Employee paid leave days"
        tests:
          - dbt_utils.accepted_range:
                min_value: 20
                max_value: 30
      - name: adresse_domicile
        description: "Employee home address"
      - name: moyen_de_deplacement
        description: "Employee means of transportation"
        tests:
        - not_null
      - name: moyen_de_deplacement_valide
        description: "Employee validated means of transportation for mobility bonus"
        tests:
          - not_null
      - name: distance_to_office_km
        description: "Employee distance to office in km"
        tests:
          - dbt_utils.accepted_range:
                min_value: 0
                inclusive: False
      - name: dbt_loaded_at
        description: "Timestamp when the record was loaded by dbt"
        tests:
          - not_null

  - name: silver_sport_activities_history
    description: "Silver layer - Sport activities history enriched with employee names"
    columns:
      - name: id_activity
        description: "Activity ID - Primary key"
        tests:
          - unique
          - not_null
      - name: id_salarie
        description: "Salarie ID - Foreign key"
        tests:
          - not_null
      - name: name_salarie
        description: "Employee first name from RH info"
        tests:
          - not_null
      - name: bu_salarie
        description: "Business unit of the employee"
        tests:
          - not_null
      - name: date_start
        description: "Activity start timestamp"
        tests:
          - dbt_utils.accepted_range:
                min_value: "'2025-01-01'::timestamp"
                max_value: "CURRENT_DATE"
      - name: type_activity
        description: "Type of sport activity"
        tests:
          - not_null
      - name: distance_m
        description: "Distance covered during the activity in meters"
      - name: date_end
        description: "Activity end timestamp"
        tests:
          - dbt_utils.expression_is_true:
                expression: "{{ column_name }} > date_start"
      - name: comments
        description: "Additional comments about the activity"
      - name: dbt_loaded_at
        description: "Timestamp when the record was loaded by dbt"
        tests:
          - not_null

  - name: silver_sport_enterprise
    description: "Silver layer - Employee sport preferences"
    columns:
      - name: id_duo
        description: "Duo ID - Primary key"
        tests:
          - unique
          - not_null
      - name: id_salarie
        description: "Salarie ID - Foreign key"
        tests:
          - not_null
      - name: type_activity
        description: "Type of sport activity"
        tests:
          - not_null
      - name: dbt_loaded_at
        description: "Timestamp when the record was loaded by dbt"
        tests:
          - not_null