version: 2

models:
  - name: silver_rh_info
    description: "Silver layer - HR information with validated transportation method"
    columns:
      - name: id_salarie
        description: "Salarie ID - Primary key"
        tests:
          - unique
          - not_null
      - name: name_salarie
        description: "Employee first name"
        tests:
          - not_null

  - name: silver_sport_activities_history
    description: "Silver layer - Sport activities history enriched with employee names"
    columns:
      - name: id_activity
        description: "Activity ID - Primary key"
        tests:
          - unique
          - not_null
      - name: id_salarie
        description: "Salarie ID - Foreign key"
        tests:
          - not_null
      - name: name_salarie
        description: "Employee first name from RH info"
      - name: date_start
        description: "Activity start timestamp"
        tests:
          - not_null
      - name: type_activity
        description: "Type of sport activity"
        tests:
          - not_null

  - name: silver_sport_enterprise
    description: "Silver layer - Employee sport preferences"
    columns:
      - name: id_duo
        description: "Duo ID - Primary key"
        tests:
          - unique
          - not_null
      - name: id_salarie
        description: "Salarie ID - Foreign key"
        tests:
          - not_null
      - name: type_activity
        description: "Type of sport activity"
        tests:
          - not_null

  - name: stg_rh_info
    description: "HR information"
    columns:
      - name: id_salarie
        description: "Salarie ID - Primary key"
        tests:
          - unique
          - not_null

  - name: stg_sport_enterprise
    description: "Employee sport preferences"
    columns:
      - name: id_duo
        description: "Duo ID - Primary key"
        tests:
          - unique
          - not_null

      - name: id_salarie
        description: "Salarie ID - Foreign key"
        tests:
          - not_null

      - name: type_activity
        description: "Type of sport activity"
        tests:
          - not_null