version: 2

sources:
  - name: raw_data
    description: "Raw source tables from the sport activities database"
    database: sport_activities_db
    schema: public
    tables:
      - name: sport_activities_history
        description: "Employee sport activities with timestamps and details"
        columns:
          - name: id_activity
            description: "Primary key - unique activity ID"
            tests:
              - unique
              - not_null
          - name: id_salarie
            description: "Employee ID who performed the activity"
            tests:
              - not_null
          - name: date_start
            description: "Activity start timestamp"
            tests:
              - not_null
          - name: type_activity
            description: "Type of sport activity"
            tests:
              - not_null
          - name: distance_m
            description: "Distance in meters (can be null)"
          - name: date_end
            description: "Activity end timestamp"
            tests:
              - not_null
          - name: comments

      - name: sport_enterprise
        description: "Employess sport activities"
        columns:
          - name: id_duo
            description: "Primary key"
            tests:
              - unique
              - not_null
          - name: id_salarie
            description: "Employee ID"
            tests:
              - not_null
          - name: type_activity
            description: "Type of sport the employee practices"
            tests:
              - not_null

      - name: rh_info
        description: "HR information for employees"
        columns:
          - name: id_salarie
            description: "Primary key - Employee ID"
            tests:
              - unique
              - not_null
          - name: first_name_salarie
            description: "Employee first name"
            tests:
              - not_null
          - name: last_name_salarie
            description: "Employee last name"
            tests:
              - not_null
          - name: bu_salarie
            description: "Business unit of the employee"
            tests:
              - not_null
          - name: salaire_brut
            description: "Gross salary"
            tests:
              - not_null
          - name: type_contrat
            description: "Contract type (CDI/CDD)"
            tests:
              - not_null
              - accepted_values:
                  values: ['CDI', 'CDD']
          - name: jours_cp
            description: "Number of vacation days"
            tests:
              - not_null
          - name: adresse_domicile
            description: "Home address"
          - name: moyen_de_deplacement
            description: "Transportation method"
            tests:
              - not_null
          - name: distance_to_office_km
            description: "Distance from home to office in kilometers"
            tests:
              - not_null
